In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv('/kaggle/input/customer-churn-dataset/customer_churn_dataset.csv')

In [3]:
data.head()

,customer_id,gender,age,marital_status,dependents,contract_type,internet_service,phone_service,multiple_lines,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,monthly_charges,total_charges,churn_status,call_duration_minutes,latitude,longitude
0,3850,Male,42,Married,3,Monthly,Fiber Optic,No,No,Yes,...,No,Yes,Yes,Yes,41.40,595.21,No,1062,-49.780269,-13.803970
1,4696,Female,76,Single,1,Yearly,DSL,No,Yes,Yes,...,No,Yes,Yes,No,46.20,940.05,No,901,56.553157,113.992914
2,5695,Female,39,Married,2,Monthly,Fiber Optic,Yes,No,Yes,...,No,No,Yes,No,43.05,919.62,No,928,80.762088,-27.906437
3,8712,Female,74,Single,3,Monthly,DSL,No,No,No,...,Yes,No,No,Yes,23.01,538.68,Yes,479,87.832819,86.922690
4,10506,Male,30,Married,3,Yearly,DSL,No,Yes,No,...,Yes,No,No,No,38.19,875.93,No,650,-88.373695,-29.320198

In [4]:
print(data.shape)
print(data.describe)
print(data.info)

(500, 21)
<bound method NDFrame.describe of      customer_id  gender  age marital_status  dependents contract_type  \
0           3850    Male   42        Married           3       Monthly
1           4696  Female   76         Single           1        Yearly
2           5695  Female   39        Married           2       Monthly
3           8712  Female   74         Single           3       Monthly
4          10506    Male   30        Married           3        Yearly
..           ...     ...  ...            ...         ...           ...
495       980574  Female   76        Married           2        Yearly
496       990832    Male   76         Single           2       Monthly
497       994515  Female   24        Married           0        Yearly
498       994922    Male   43        Married           0        Yearly
499       997121  Female   54        Married           1        Yearly

    internet_service phone_service multiple_lines online_security  ...  \
0        Fiber Optic            No             No             Yes  ...
1                DSL            No            Yes             Yes  ...
2        Fiber Optic           Yes             No             Yes  ...
3                DSL            No             No              No  ...
4                DSL            No            Yes              No  ...
..               ...           ...            ...             ...  ...
495      Fiber Optic           Yes            Yes             Yes  ...
496      Fiber Optic           Yes            Yes             Yes  ...
497              DSL            No             No             Yes  ...
498      Fiber Optic           Yes            Yes              No  ...
499              DSL            No            Yes             Yes  ...

    device_protection tech_support streaming_tv streaming_movies  \
0                  No          Yes          Yes              Yes
1                  No          Yes          Yes               No
2                  No           No          Yes               No
3                 Yes           No           No              Yes
4                 Yes           No           No               No
..                ...          ...          ...              ...
495               Yes           No          Yes               No
496               Yes          Yes          Yes               No
497               Yes          Yes          Yes              Yes
498                No          Yes          Yes               No
499               Yes          Yes           No               No

    monthly_charges  total_charges  churn_status call_duration_minutes  \
0             41.40         595.21            No                  1062
1             46.20         940.05            No                   901
2             43.05         919.62            No                   928
3             23.01         538.68           Yes                   479
4             38.19         875.93            No                   650
..              ...            ...           ...                   ...
495           58.12         139.76            No                   428
496           81.67         434.50            No                   370
497           93.68         928.09            No                   439
498           85.05         998.00            No                   238
499           46.16         812.59            No                  1142

      latitude   longitude
0   -49.780269  -13.803970
1    56.553157  113.992914
2    80.762088  -27.906437
3    87.832819   86.922690
4   -88.373695  -29.320198
..         ...         ...
495  75.487045    9.273929
496 -22.238678  164.152687
497 -28.324261   40.788933
498  31.974046  105.205718
499  40.887085  100.463755

[500 rows x 21 columns]>
<bound method DataFrame.info of      customer_id  gender  age marital_status  dependents contract_type  \
0           3850    Male   42        Married           3       Monthly
1           4696  Female   76         Single           1        Yearly
2           5695  Female   39        Married           2       Monthly
3           8712  Female   74         Single           3       Monthly
4          10506    Male   30        Married           3        Yearly
..           ...     ...  ...            ...         ...           ...
495       980574  Female   76        Married           2        Yearly
496       990832    Male   76         Single           2       Monthly
497       994515  Female   24        Married           0        Yearly
498       994922    Male   43        Married           0        Yearly
499       997121  Female   54        Married           1        Yearly

    internet_service phone_service multiple_lines online_security  ...  \
0        Fiber Optic            No             No             Yes  ...
1                DSL            No            Yes             Yes  ...
2        Fiber Optic           Yes             No             Yes  ...
3                DSL            No             No              No  ...
4                DSL            No            Yes              No  ...
..               ...           ...            ...             ...  ...
495      Fiber Optic           Yes            Yes             Yes  ...
496      Fiber Optic           Yes            Yes             Yes  ...
497              DSL            No             No             Yes  ...
498      Fiber Optic           Yes            Yes              No  ...
499              DSL            No            Yes             Yes  ...

    device_protection tech_support streaming_tv streaming_movies  \
0                  No          Yes          Yes              Yes
1                  No          Yes          Yes               No
2                  No           No          Yes               No
3                 Yes           No           No              Yes
4                 Yes           No           No               No
..                ...          ...          ...              ...
495               Yes           No          Yes               No
496               Yes          Yes          Yes               No
497               Yes          Yes          Yes              Yes
498                No          Yes          Yes               No
499               Yes          Yes           No               No

    monthly_charges  total_charges  churn_status call_duration_minutes  \
0             41.40         595.21            No                  1062
1             46.20         940.05            No                   901
2             43.05         919.62            No                   928
3             23.01         538.68           Yes                   479
4             38.19         875.93            No                   650
..              ...            ...           ...                   ...
495           58.12         139.76            No                   428
496           81.67         434.50            No                   370
497           93.68         928.09            No                   439
498           85.05         998.00            No                   238
499           46.16         812.59            No                  1142

      latitude   longitude
0   -49.780269  -13.803970
1    56.553157  113.992914
2    80.762088  -27.906437
3    87.832819   86.922690
4   -88.373695  -29.320198
..         ...         ...
495  75.487045    9.273929
496 -22.238678  164.152687
497 -28.324261   40.788933
498  31.974046  105.205718
499  40.887085  100.463755

[500 rows x 21 columns]>

In [5]:
x=data.drop('churn_status',axis=1)
y=data['churn_status']

In [6]:
label_encoder=LabelEncoder()
x_encoded=x.apply(label_encoder.fit_transform)

In [7]:
x_encoded.head()

,customer_id,gender,age,marital_status,dependents,contract_type,internet_service,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,monthly_charges,total_charges,call_duration_minutes,latitude,longitude
0,0,1,24,0,3,0,1,0,0,1,0,0,1,1,1,196,278,372,102,225
1,1,0,58,1,1,1,0,0,1,1,0,0,1,1,0,217,465,323,396,419
2,2,0,21,0,2,0,1,1,0,1,1,0,0,1,0,202,443,335,469,202
3,3,0,56,1,3,0,0,0,0,0,1,1,0,0,1,110,245,165,494,380
4,4,1,12,0,3,1,0,0,1,0,0,1,0,0,0,182,421,231,0,200

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x_encoded,y,test_size=0.25,random_state=21)

In [9]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [10]:
y_pred=model.predict(x_test)

In [11]:
accuracy=accuracy_score(y_test,y_pred)
print('accuracy :',accuracy)

accuracy : 0.72